# Generated by Django 5.2.16 on 2026-07-28 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='link',
            name='portal_link_categor_da3a44_idx',
        ),
        migrations.RemoveField(
            model_name='link',
            name='category',
        ),
        migrations.RemoveField(
            model_name='link',
            name='description',
        ),
        migrations.RemoveField(
            model_name='link',
            name='icon',
        ),
    ]
