# Generated by Django 5.2.16 on 2026-07-28 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_remove_link_portal_link_categor_da3a44_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.RenameModel(
            old_name='Department',
            new_name='Category',
        ),
        migrations.RenameField(
            model_name='link',
            old_name='departments',
            new_name='categories',
        ),
        migrations.RenameIndex(
            model_name='category',
            new_name='portal_cate_name_f74444_idx',
            old_name='portal_depa_name_9a1563_idx',
        ),
        migrations.RenameIndex(
            model_name='category',
            new_name='portal_cate_is_acti_819f36_idx',
            old_name='portal_depa_is_acti_4f69fa_idx',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='departments',
            new_name='categories',
        ),
        migrations.AddIndex(
            model_name='store',
            index=models.Index(fields=['name'], name='portal_stor_name_d4db0d_idx'),
        ),
        migrations.AddIndex(
            model_name='store',
            index=models.Index(fields=['is_active'], name='portal_stor_is_acti_f4fcd3_idx'),
        ),
        migrations.AddField(
            model_name='link',
            name='stores',
            field=models.ManyToManyField(blank=True, related_name='links', to='portal.store'),
        ),
        migrations.AddField(
            model_name='user',
            name='stores',
            field=models.ManyToManyField(blank=True, related_name='users', to='portal.store'),
        ),
    ]
