# Generated by Django 5.2.16 on 2026-07-28 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_store_rename_department_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='store',
            name='slug',
        ),
        migrations.AlterField(
            model_name='user',
            name='categories',
            field=models.ManyToManyField(blank=True, help_text='Categories this user belongs to. Determines which links they can see.', related_name='users', to='portal.category'),
        ),
    ]
