# Generated by Django 5.2.16 on 2026-10-08 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('portal', '0004_remove_category_slug_remove_store_slug_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name_plural': 'Categories'},
        ),
        migrations.AddField(
            model_name='user',
            name='inactivity_policy',
            field=models.CharField(choices=[('none', 'No Deactivation'), ('7_days', '1 Week'), ('10_days', '10 Days')], default='none', help_text='Automatically deactivate the account if not logged in for this duration.', max_length=20, verbose_name='Deactivation Policy'),
        ),
        migrations.AddField(
            model_name='user',
            name='last_activated_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp of when the user was manually activated or joined.', null=True, verbose_name='Last Activated At'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['inactivity_policy'], name='portal_user_inactiv_f8f0ed_idx'),
        ),
    ]
