# Generated by Django 5.2.16 on 2026-10-08 07:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_alter_category_options_user_inactivity_policy_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InactivityPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text="Optional label (e.g. '1 Day', '1 Week'). If blank, will default to '[X] Days'.", max_length=100)),
                ('days', models.PositiveIntegerField(help_text='Number of days of inactivity before automatic deactivation (e.g., 1, 2, 3, 7, 10).', unique=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this period option is active and available in selection dropdowns.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Inactivity Period',
                'verbose_name_plural': 'Inactivity Periods',
                'ordering': ['days'],
            },
        ),
        migrations.RemoveIndex(
            model_name='user',
            name='portal_user_inactiv_f8f0ed_idx',
        ),
        migrations.RemoveField(
            model_name='user',
            name='inactivity_policy',
        ),
        migrations.AddField(
            model_name='user',
            name='inactivity_period',
            field=models.ForeignKey(blank=True, help_text='Select an inactivity option, or leave empty for No Deactivation.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='portal.inactivityperiod', verbose_name='Inactivity Period'),
        ),
    ]
